baseurl = "https://dick-the-deployer.github.io"
languageCode = "en-us"
title = "Dick the Deployer"
theme = "purehugo"

[params]
  githubName = "dick-the-deployer/dick"
  slackName = "dickthedeployer"
  description = "Dockerized Continuous Delivery"
