baseurl = "http://dickthedeployer.com"
languageCode = "en-us"
title = "Dick the Deployer"
theme = "purehugo"

[params]
  githubName = "dick-the-deployer/dick"
  description = "Dockerized Continuous Delivery"
